---
# Source: nginx-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  labels:
    helm.sh/chart: nginx-server-0.1.0
    app.kubernetes.io/name: nginx-server
    app.kubernetes.io/instance: nginx-server
    app.kubernetes.io/version: "1.29.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-server
---
# Source: nginx-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    helm.sh/chart: nginx-server-0.1.0
    app.kubernetes.io/name: nginx-server
    app.kubernetes.io/instance: nginx-server
    app.kubernetes.io/version: "1.29.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
# Source: nginx-server/templates/ingress.yaml
# environments\staging\helm\nginx-server\templates\ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-server
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80}]"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
spec:
  ingressClassName: alb
  rules:
    - host: nginx.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-server
                port:
                  number: 80
